language: 
  - node_js

node_js:  
  - stable

dist: 
  - trusty

addons:
  sonarcloud:
    organization: "benyamin-rafaeli"
    token:
      secure: "74db23d9f963d84e99b4efa23cea11b12dae3ed0" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner

# if using Ubuntu 16 need this library
# # https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

# &defaults
defaults: 
  script:
    # start local json server
    - npm run srv &
    # this is a percy token 
    # - export PERCY_TOKEN=24a53b2592a5de794b3ef8fb9e76fb33bfda5b57baff7a3ba6495d622407b4b4
    # - npx percy exec -- cypress run 
    # this is run for cypress dashboard
    - npx cypress run
    # - npx cypress run --record --key 02ac3e53-8afa-4d78-95a1-fd6e010aa9c4 --group 1x-chrome --browser chrome --parallel
    # - npx percy exec -- cypress run --record --key 02ac3e53-8afa-4d78-95a1-fd6e010aa9c4 --group 1x-chrome --browser chrome --parallel
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true

jobs:
  include:
    # we have multiple jobs to execute using just a single stage
    # but we can pass group name via environment variable to Cypress test runner
    - stage: test
      env:
        - STAGE_NAME="1x-electron on Travis CI"
      <<: *defaults
    # run tests in parallel by including several test jobs with same name variable
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults

after_script:
  - bash ./run.sh
  - curl --request GET 'https://api.telegram.org/bot1148229624:AAHRtV1VHL7LWSLEWDR7nOqMZ42zfGG-cBk/sendmessage?chat_id=500415337&text=Activated Tests Suite'
  
