version: '3'
services: 
    e2e:
        image: cypress
        build: .
        container_name: cy_docker
        # command: npm run cy && npx mochawesome-merge cypress/reports/mocha/*.json > cypress/mochareports/report.json && npx marge cypress/mochareports/*.json -f report -o cypress/mochareports                
        volumes: 
            - /Users/benjamin/report:/app/cypress/videos
            - /Users/benjamin/report:/app/cypress/screenshots
            - /Users/benjamin/report:/app/cypress/reports
            - /Users/benjamin/report:/app/cypress/mochareports

        # # # addons:
        # sonarcloud:
        #     organization: "benyamin-rafaeli"
        #     token:
        #     secure: "9d5f34f1af51656663ba00fc362d0a80b720e918" # encrypted value of travis        
        # script:
        # # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
        # - sonar-scanner