version: '3'
services: 
    e2e:
        image: cypress
        build: .
        container_name: cy_docker
        command: npm run cy
        volumes: 
            - /Users/benjamin/report:/app/cypress/videos
            - /Users/benjamin/report:/app/cypress/screenshots


            